### PR TITLE
Module 1 : Hello Microverse Project

### PR DESCRIPTION
**Pull request by tsheporamantso**
**In this Project I have successfully **
1) Ran linter folders and files 
2) Added HTML file with the text 
3) Styled HTML element 
4) Added node_modules and test.md on gitignore file

### CODE REVIEW

**Review by nedjwab — CHANGES_REQUESTED** [review]
# Changes Required ♻️
### Hi  @tsheporamantso 

Nice job, you are almost there.



## (Highlights) Good Points: :
- Good implementation of some of the project requirements  ✔
- GitHub flow was correctly used ✔.

## (Changes Required) Aspects to improve: ♻️
You did great implementing some of the project requirements, but you still have some issues: 
 ```

[ ] good job using the microverse README template 🔥🔥, kindly customize it using your information: project's name ,details ...
[ ] Kindly add a descriptive title to your PR. Pull Request should have a descriptive title telling you what changes are inside. (example: setup linters).🤓
```

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @tsheporamantso, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

 - ✔️

## Aspects to improve ♻️

- [ ] Check the comments under the review.
 - [ ] The README is missing information necessary for the project. Microverse changed the README template used in their projects so the students should follow [this template](https://github.com/microverseinc/readme-template). Kindly change the README to this template and make sure that you customized the headers with your information and information about this specific project as the previous code reviewer asked.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @tsheporamantso   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!



## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] As requested by the previous reviewer, kindly make sure to edit your README file and use the provided and professional [Microverse README template](https://github.com/microverseinc/readme-template) and customize it according to your project in order to make your repo professional. :wink:  
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

 - Good implementation of some of the project requirements ✔
 - GitHub flow was correctly used ✔.

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] Unfortunately, you did not make any changes requested by the previous reviewers. The README is missing information necessary for the project. Microverse changed the README template used in their projects so the students should follow [this template](https://github.com/microverseinc/readme-template). Kindly change the README to this template and make sure that you customized the headers with your information and information about this specific project as the previous code reviewer asked.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by jerryowusu — COMMENTED** [review]
Hi @tsheporamantso  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

soclose1


 ## Highlights
Good pull request summary :heavy_check_mark: 
Followed GitHub flow :heavy_check_mark: 

 ## Required Changes ♻️
- [ ]  I can see you have put in a lot of effort in updating the readme on the main branch. :+1:  However, all the changes you make should be on the feature branch that you are trying to merge and not the main branch. Unfortunately you have deleted the readme file on this branch. Kindly update this branch with the readme file on the main branch, and customize it :pray:  

_Check the comments under the review._

## Optional suggestions
- [ ] [OPTIONAL] Kindly note that for your project to meet standard best practice, you do not have to merge a project until it has been approved. :wink: 

- [ ] I do not see linters set up in your project, Kindly ensure that linters are properly set up and working to help you achieve best standard practices. :wink: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
